export const ROUTES = {
   NOT_FOUND: '*',
   INDEX: '/',
   PROFILE: '/profile',
   BOARDS: '/boards',
   PARTICIPANTS: '/participants',
   ISSUES: '/issues',
   SIGN_IN: '/sign-in',
   SIGN_UP: '/sign-up',
   FORGOT: '/forgot-password/:userId',
   BOARDS_ID: '/boards/:workspaceId',
   COLUMN_ID: '/boards/:workspaceId/:boardId',
   PROFILE_ID: '/profile/:id',
   PARTICIPANTS_ID: '/participants/:workspaceId',
   ISSUES_ID: '/issues/:workspaceId',
}
